# =============================================================================
# REFERENCES
# =============================================================================
GENOM_PATH: /mnt/scratch1/projects/qcGenes.git/data/ref/GRCh38.101/Homo_sapiens.GRCh38.dna.primary_assembly.fa.gz
ANNOT_PATH: /mnt/scratch1/projects/qcGenes.git/data/ref/GRCh38.101/Homo_sapiens.GRCh38.101.gtf.gz
TRANS_PATH: /mnt/scratch1/projects/qcGenes.git/data/ref/GRCh38.101/Homo_sapiens.GRCh38.cdna.all.fa.gz

# GENOM_URL: ftp://ftp.ensembl.org/pub/release-99/fasta/homo_sapiens/dna/Homo_sapiens.GRCh38.dna_sm.alt.fa.gz
# ANNOT_URL: ftp://ftp.ensembl.org/pub/release-99/gtf/homo_sapiens/Homo_sapiens.GRCh38.99.gtf.gz
# TRANS_URL: ftp://ftp.ensembl.org/pub/release-99/fasta/homo_sapiens/cdna/Homo_sapiens.GRCh38.cdna.all.fa.gz
# GENE SET ENRICHMENT ANALYSIS (GSEA)
GSEA_INPUT_GENES: 500                                  # NUMBER OF GENES IN FOREGROUND SET FOR GSEA
GSEA_PATHWAY_REPRESENTATION_PERCENTAGE_CUTOFF: 0.00001 # 0.1 for a min of 10% of the pathway genes
GSEA_INPUTGENES_REPRESENTATION_PERCENTAGE_CUTOFF: 0.05 # 0.1 for a min of 10% of the input genes
GSEA_TABLE_PADJ_CUTOFF: 0.05
GSEA_PLOT_PADJ_CUTOFF2: 0.05


GS2D_PATH: data/ref/gs2d/20180416_gene2mesh.tsv
GS2D_URL: http://cbdm-01.zdv.uni-mainz.de/~jfontain/downloads/20180416_gene2mesh.tsv

BOWTIE_IDX_DIR: /mnt/scratch1/projects/qcGenes.git/data/ref/bowtie2
# BOWTIE_IDX_PATH: /mnt/scratch1/projects/qcGenes.git/data/ref/bowtie2/GCA_000001405.15_GRCh38_no_alt_analysis_set.fna.bowtie_index.tar.gz
BOWTIE_IDX_FILE1: /mnt/scratch1/projects/qcGenes.git/data/ref/bowtie2/GRCh38_noalt_as.1.bt2
BOWTIE_IDX_URL: ftp://ftp.ncbi.nlm.nih.gov/genomes/archive/old_genbank/Eukaryotes/vertebrates_mammals/Homo_sapiens/GRCh38/seqs_for_alignment_pipelines/GCA_000001405.15_GRCh38_no_alt_analysis_set.fna.bowtie_index.tar.gz
BOWTIE_IDX: /mnt/scratch1/projects/qcGenes.git/data/ref/bowtie2/GRCh38_noalt_as


# USE MSIGDB DATA URLS FROM https://data.broadinstitute.org/gsea-msigdb/msigdb/release/7.1/
MSIGDB_PATH: /mnt/scratch1/projects/qcGenes.git/data/ref/msigdb/c2.cp.v7.4.symbols.gmt
MSIGDB_URL: https://data.broadinstitute.org/gsea-msigdb/msigdb/release/7.4/c2.cp.v7.4.symbols.gmt
MSIGDB_POSITIONAL_PATH: /mnt/scratch1/projects/qcGenes.git/data/ref/msigdb/c1.cp.v7.4.symbols.gmt
MSIGDB_POSITIONAL_URL: https://data.broadinstitute.org/gsea-msigdb/msigdb/release/7.4/c1.cp.v7.4.symbols.gmt

# =============================================================================
# SEQQSCORER
# =============================================================================
SPECIES_COMMON_NAME: human

WRAPPER_SCRIPT_READS_ALL_ANNO_PY: workflow/scripts/wrapper_annotation.py
WRAPPER_SCRIPT_READS_ALL_ANNO_ANN_R: workflow/scripts/readsAnno.R
WRAPPER_SCRIPT_READS_ALL_ANNO_TSS_R: workflow/scripts/readsAnnoTSS.R
WRAPPER_SCRIPT_READS_ALL_ANNO_ANN_R_NAME: readsAnno.R
WRAPPER_SCRIPT_READS_ALL_ANNO_TSS_R_NAME: readsAnnoTSS.R

WRAPPER_SCRIPT_READS_ANNO_PY: lib/seqQscorer.git/example_dataset/reads_annotation/wrapper_reads_annotation.py
WRAPPER_SCRIPT_READS_ANNO_R: lib/seqQscorer.git/example_dataset/reads_annotation/readsAnno.R
WRAPPER_SCRIPT_READS_ANNO_R_NAME: readsAnno.R

WRAPPER_SCRIPT_TSS_ANNO_PY: lib/seqQscorer.git/example_dataset/tss_annotation/wrapper_tss_annotation.py
WRAPPER_SCRIPT_TSS_ANNO_R: lib/seqQscorer.git/example_dataset/tss_annotation/readsAnnoTSS.R
WRAPPER_SCRIPT_TSS_ANNO_R_NAME: readsAnnoTSS.R

# =============================================================================
# VARIABLES
# =============================================================================
MAX_READS: 2000000 # Max number of reads to download in each FASTQ file
MAX_THREADS: 4
BOWTIE2_THREADS: 4

# GSEA_TABLE_PADJ_CUTOFF: 0.5
# GSEA_PLOT_PADJ_CUTOFF2: 0.15

MAX_DATASET_P_VS_GROUP_CORRELATION: 0.5
MIN_DATASET_N_DEG: 20

# =============================================================================
# LOG DIRERCTORIES
# =============================================================================
LOG_DIR_DW_REF: data/logs/ref
LOG_DIR_DW_DATASETS: data/logs/datasets



